FROM golang:alpine

RUN addgroup -g 1000 jenkins ; adduser -u 1000 -G jenkins jenkins -D

RUN apk update && \
    apk add --no-cache git ca-certificates tzdata gcc musl-dev && \
    update-ca-certificates

WORKDIR /work/

COPY . .

# Fetch dependencies.
RUN go get -d -v
